service: innovation-arts

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1	
  memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app
    packRequirements: false

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'